# Generated by Django 3.1.1 on 2020-09-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200908_2125'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_user_author',
        ),
    ]
